name: dotnet core - build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.202
    - name: Build with dotnet
      run: dotnet build --configuration Release
    - name: Run Tests
      run: dotnet test
